import:
  - control/keyboard/qwerty
  - control/keyboard/qwerty/arrange
  - control/keyboard/qwerty/client
  - control/keyboard/qwerty/detach
  - control/keyboard/qwerty/focus
  - control/keyboard/qwerty/focus_by_number
  - control/keyboard/qwerty/group
  - control/keyboard/qwerty/layout
  - control/keyboard/qwerty/menu
  - control/keyboard/qwerty/move
  - control/keyboard/qwerty/move_by_number
  - control/keyboard/qwerty/zoom
  - control/mouse
  - display/client
  - display/color/nougad
  - display/desktop/xsetroot
  - display/notice
  - display/status/spacer
  - display/status/music/mpd
  - display/status/volume
  - display/status/power
  - display/status/acpi/thermal
  - display/status/network
  - display/status/load
  - display/status/time
  - display/tags

prefer:
  terminal: gnome-terminal
  browser: icecat
  editor: mousepad
  filer: thunar

display:
  bar: top
  font: "xft:Monospace:pixelsize=10"
  border: 1
  column:
    mode: default
    rule: |
      /gimp/ -> 82+18
      /im/   -> 80+20
      /.*/ -> 62+38 # Golden Ratio
  client:
    rule: |
      /psi/ tags=1:im
      /Pidgin/ tags=1:im
      /(CSSH|cssh)/ tags=cssh
      /Firefox/ tags=4:web
      /IceCat/ tags=4:web
      /shellwin/ tags=3:shell
      /Thunderbird:/ tags=2:mail
      /claws-mail:/ tags=2:mail
      /Skype:/ tags=1:im
      /gimp/ tags=gimp
      /wireshark/ tags=ws
      /Eclipse/ tags=ecl
      /trayer/ tags=/./
  status:
    music:
      mpd:
        mouse_action:
          right_click: launch_gmpc
    power:
      battery:   BAT0
    volume:
      mixer:    Master
    network:
      instances:
        - interface: wlan0
        - interface: eth0
        - interface: tun0
    thermal:
      mouse_action:
        right_click: toggle_ibm_fan
    notice:
      control:
        mouse_action:
          wheel_up: focus_next_view
          wheel_down: focus_previous_view

control:
  keyboard:
    grabmod: Mod4

    mod:     Mod4
    move:    Mod4-Shift
    swap:    Mod4-w
    view:    Mod4-Shift-v
    group:   Mod4-g
    layout:  Mod4-z
    arrange: Mod4-Shift-z
    prev: p
    next: n

  keyboard_action:
    ${mod}-o: run_program_from_menu
    ${mod}-Return: launch_terminal
    ${mod}-p: nil
    XF86ScreenSaver: lock_display
    Print: screenshot

  action:
    reload: |
      launch "pkill mpd"
      launch "pkill seahorse-daemon"
      launch "pkill xscreensaver"
    launch_terminal: |
      work = ENV['HOME']
      require 'fileutils'
      FileUtils.cd work do
        launch CONFIG['prefer']['terminal']
      end
    launch_gmpc: launch "gmpc"
    show_acpi_stats: dialog `acpitool`
    lock_display: launch "xscreensaver-command", "-lock"
    screenshot:   launch "scrot"
    toggle_ibm_fan: |
      procfile = "/proc/acpi/ibm/fan"
      status = File.read(procfile).gsub(/.*\nlevel:\t\t([a-z0-9]*)\n.*/m, "\\1")
      File.open procfile, "w" do |f|
        case status
        when "auto"       then f.puts "level disengaged"
        when "disengaged" then f.puts "level auto"
        end
      end

  event:
    Urgent: |
      id, type = argv

      message =
        case type
        when 'Client' then Client.new(id).label.read
        else id
        end

script:
  - after: |
      launch "xscreensaver"
      launch "mpd"
      launch "seahorse-daemon"
      ENVVARS=`gnome-keyring-daemon --components=pkcs11,secrets,ssh,gpg --start`
      ENVVARS.each_line do |v| name, value = v.strip.split("="); ENV[name] = value; puts "setting #{name} to #{value}" end

