import:
  - control/keyboard/qwerty
  - control/mouse
  - display/client
  - display/color/nougad
  - display/desktop/xsetroot
  - display/notice
  - display/status/spacer
  - display/status/music/mpd
  - display/status/volume/amixer
  - display/status/power/acpi
  - display/status/network/vpn
  - display/status/network/ipaddr
  - display/status/system/loadavg
  - display/status/time
  - display/tags

prefer:
  terminal: urxvt
  browser: icecat
  editor: mousepad
  filer: thunar

display:
  bar: top
  font: "-*-fixed-medium-r-*-*-12-*-*-*-*-*-*-*"
  border: 1
  column:
    mode: default
    rule: |
      /gimp/ -> 82+18
      /im/   -> 80+20
      /.*/ -> 62+38 # Golden Ratio
  client:
    - /.*psi.*/ : 1:im
    - /Pidgin.*/ : 1:im
    - /.*(CSSH|cssh).*/ : cssh
    - /VLC.*/ : media
    - /Firefox.*/ : 4:web
    - /IceCat.*/ : 4:web
    - /shellwin.*/ : 3:shell
    - /Thunderbird:.*/ : 2:mail
    - /Skype:.*/ : 1:im
    - /gimp/ : gimp
    - /wireshark/: ws
    - /.*Eclipse.*/: ecl
  status:
    mpd:
      mouse_action:
        right_click: launch_gmpc
    vpn:
      device:   tun0
    acpi:
      battery:   BAT0
    amixer:
      mixer:    Master
      position: 6
    time:
      position: 7
    ipaddr:
      path_to_ip: /sbin/ip
      position: 8

control:
  keyboard:
    grabmod: Mod4

    mod:     Mod4
    move:    Mod4-Shift
    swap:    Mod4-w
    view:    Mod4-Shift-v
    group:   Mod4-g
    layout:  Mod4-z
    arrange: Mod4-Shift-z
    prev: p
    next: n

  keyboard_action:
    ${mod}-o: run_program_from_menu
    ${mod}-Return: launch_terminal
    ${mod}-p: nil
    XF86ScreenSaver: lock_display
    Print: screenshot

  action:
    launch_terminal: |
      work = ENV['HOME']
      require 'fileutils'
      FileUtils.cd work do
        launch CONFIG['prefer']['terminal'], "-name", "shellwin"
      end
    launch_gmpc: launch "gmpc"
    show_acpi_stats: dialog `acpitool`
    lock_display: launch "xscreensaver-command", "-lock"
    screenshot:   launch "scrot"

script:
  - after: |
      launch "xscreensaver"
      launch "mpd"

