script:
  - after: |
      action 'rehash'

control:
  action:

    reload: |
      # reload this wmii configuration
      Wmiirc::Loader.reload

    rehash: |
      # scan for available programs and actions
      @programs = find_programs(ENV['PATH'].gsub(/\$([A-Z0-9_]+)/) do |x| ENV[x[1..-1]] end.squeeze(':').split(':'))

    clear: |
      # these browsers' "restore session" feature does
      # not work unless the whole process group is killed
      system 'killall', 'opera',
        'chromium', 'chromium-browser',
        'firefox', 'firefox-bin',
        'thunderbird', 'thunderbird-bin'

      clients.each {|c| c.kill rescue nil }

    kill: |
      # kill the window manager only; do not touch the clients!
      fs.ctl.write 'quit'

    quit: |
      # kill both clients and window manager
      action 'clear'
      action 'kill'
